config/routes.rb
FortySixerOnRails::Application.routes.draw do
 
  match '/help',    to: 'static_pages#help',      via: 'get'
  match '/about',   to: 'static_pages#about',     via: 'get'
  match '/contact', to: 'static_pages#contact',   via: 'get'
 

  resources :users
  match '/signup', to: 'users#new',    via:'get'

  resources :treks

  get '/mountains' => 'mountains#index'
  get '/mountains/:id' => 'mountains#show', as: 'mountain'

  root 'static_pages#home'

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  post '/sessions' => 'sessions#create'

end

app/models/trek.rb
class Trek < ActiveRecord::Base
  has_many :trek_mountains
  has_many :mountains, :through => :trek_mountains


  def mountains=(mountains_array)
    Mountain.find_mountain_from_mountains_array(mountains_array).each do |mountain|
      self.add_mountain(mountain)
    end
  end

  def add_mountain(mountain)
    self.trek_mountains.build(:mountain => mountain)
  end


  def self.find_trek_from_treks_array(treks_array)
    treks_array.collect do |trek|
      Trek.find_by(:name => trek)
    end
  end

end

app/controllers/treks_controller.rb
class TreksController < ApplicationController
  skip_before_action :login_required, :only => [:index, :show]
  before_action :set_trek, only: [:show, :edit, :update, :destroy]
  before_action :set_mountains, only: [:show]

  # GET /treks
  # GET /treks.json
  def index
    @treks = Trek.all
  end

  # GET /treks/1
  # GET /treks/1.json
  def show
  end

  # GET /treks/new
  def new
    @trek = Trek.new
  end

  # GET /treks/1/edit
  def edit
  end

  # POST /treks
  # POST /treks.json
  def create
    @trek = Trek.new(trek_params)

    respond_to do |format|
      if @trek.save && logged_in?
        format.html { redirect_to "/users/#{current_user.id}", notice: 'Trek was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trek }
      elsif @trek.save
        format.html { redirect_to @trek, notice: 'Trek was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trek }
      else
        format.html { render action: 'new' }
        format.json { render json: @trek.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treks/1
  # PATCH/PUT /treks/1.json
  def update
    @trek.trek_mountains.clear
    respond_to do |format|
      if @trek.update(trek_params)
        format.html { redirect_to @trek, notice: 'Trek was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trek.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treks/1
  # DELETE /treks/1.json
  def destroy
    @trek.destroy
    respond_to do |format|
      format.html { redirect_to treks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trek
      @trek = Trek.find(params[:id])
    end

    def set_mountains
      @mountains = Mountain.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trek_params
      params.require(:trek).permit(:name, :url, :diff, :distance, :duration, :desc, :mountains=>[])
    end
end

app/helpers/treks_helper.rb
module TreksHelper
end

app/views/treks/_form.html.erb
<%= form_for(@trek) do |f| %>
  <% if @trek.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trek.errors.count, "error") %> prohibited this trek from being saved:</h2>

      <ul>
      <% @trek.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class= "panel panel-default col-md-3 col-md-offset-1" >
  <div class="panel-body">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <% Mountain.order(:name).each do |mountain| %>
      <%= check_box_tag "trek[mountains][]", mountain.name, @trek.mountains.include?(mountain), id: mountain.name, value: mountain.name %> 
      <%= label_tag "#{mountain.name}" %></br>
    <% end %></br>

    <div class="field">
      <%= f.label :url, 'Navigation' %><br>
      <%= f.text_field :url %>
    </div>

   <div class="field">
      <%= f.label :diff %><br>
      <%= f.select :diff, [['Difficult'], ['Moderate'], ['Easy']] %>
    </div>

    <div class="field">
      <%= f.label :distance %><br>
      <%= f.text_field :distance %>
    </div>


    <div class="field">
      <%= f.label :duration %><br>
      <%= f.select :duration, [['Multiple-days'], ['Full-day'], ['Half-day']] %>
    </div>

    <div class="field">
      <%= f.label :desc %><br>
      <%= f.text_area :desc %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/treks/edit.html.erb
<h1>Editing trek</h1>

<%= render 'form' %>

<%= link_to 'Show', @trek %> |
<%= link_to 'Back', treks_path %>

app/views/treks/index.html.erb
<div class="panel panel-default col-md-8 pull-left">
  <div class="panel-heading">Recommended hikes:</div>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Navigation</th>
          <th>Diff</th>
          <th>Distance</th>
          <th>Duration</th>
          <th>Desc</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @treks.each do |trek| %>
          <tr>
            <td><%= link_to trek.name, trek %></td>
            <td><%= link_to_if(trek.url, 'Navigation', trek.url) %></td>
            <td><%= trek.diff %></td>
            <td><%= trek.distance %></td>
            <td><%= trek.duration %></td>
            <td><%= trek.desc %></td>
            <td><%= link_to 'Destroy', trek, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Trek', new_trek_path %>

app/views/treks/new.html.erb
<%= render 'form' %>

app/views/treks/new.js.erb
$('#hikes').hide().after('<%= j render 'treks/form' %>');

app/views/treks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default col-md-3">
  <div class="panel-body">
    <p>
      <strong>Name:</strong>
      <%= link_to_if(@trek.url, @trek.name, @trek.url) %>
    </p>

    <p>
      <strong>Diff:</strong>
      <%= @trek.diff %>
    </p>

    <p>
      <strong>Distance:</strong>
      <%= @trek.distance %>
    </p>

    <p>
      <strong>Duration:</strong>
      <%= @trek.duration %>
    </p>

    <p>
      <strong>Desc:</strong>
      <%= @trek.desc %>
    </p>
    
    <p>
    <strong>46-R mountains:</strong></br>
      <% @trek.mountains.each do |mountain| %>
        <%= mountain.name %></br>
      <%end%>
      </p>
    
  
  </div>
</div>