config/routes.rb
FortySixerOnRails::Application.routes.draw do
 
  match '/help',    to: 'static_pages#help',      via: 'get'
  match '/about',   to: 'static_pages#about',     via: 'get'
  match '/contact', to: 'static_pages#contact',   via: 'get'
 

  resources :users
  match '/signup', to: 'users#new',    via:'get'

  resources :treks

  get '/mountains' => 'mountains#index'
  get '/mountains/:id' => 'mountains#show', as: 'mountain'

  root 'static_pages#home'

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  post '/sessions' => 'sessions#create'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><a href="http://www.adk46er.org/">ADK 46-R</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
<!--       <nav> -->
      <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if logged_in? %>
            <a class="navbar-brand" href="/users/<%= current_user.id %>">ADK 46-R Tracker</a>
          <% else %>
            <a class="navbar-brand" href=<%= root_path %>>ADK 46-R Tracker</a>
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Mountains', mountains_path %></li>
            <li><%= link_to 'Hikes', treks_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><a>Logged in as: <%= current_user.email %></a></li>
              <li><%= link_to "logout", logout_path %></li>
            <% else %>
              <li><%= link_to 'Login', login_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>
<!--       </nav> -->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FortySixerOnRails | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="background">
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>